version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Print Environment Variables
          command: printenv
      - run:
          name: Show Git Status
          command: git status
      - run:
          name: Your build steps
          command: |
            # Add your build commands here

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

